package rand

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
)

const (
	// The min number of bytes to be used for each session token
	MinBytesPerToken = 32
)

func Bytes(n int) ([]byte, error) {
	b := make([]byte, n) // placeholder to put randomly generated byte string into
	nRead, err := rand.Read(b)
	if err != nil {
		return nil, fmt.Errorf("bytes: %w", err)
	}
	if nRead < n {
		return nil, fmt.Errorf("bytes: did not read enough random bytes")
	}
	return b, nil
}

// String returns a random string using crypto/rand.
// n is the number of bytes being used to generate the random string
func String(n int) (string, error) {
	b, err := Bytes(n)
	if err != nil {
		return "", fmt.Errorf("string: %w", err)
	}
	return base64.URLEncoding.EncodeToString(b), nil
}
